### ISSUE TITLE
组件间如何通信有没有更好的解偶方式？

### ISSUE THREAD

**Issue by willpyshan13** [bilibili/BRouter#2]
组件间如何通信有没有更好的解偶方式？

**Comment by dieyidezui** [comment]
我们倾向于通过定义的接口通信

**Comment by willpyshan13** [comment]
> 我们倾向于通过定义的接口通信

接口下沉吗？还是怎么定义这个

**Comment by dieyidezui** [comment]
> > 我们倾向于通过定义的接口通信
> 
> 接口下沉吗？还是怎么定义这个

原则上最好是为每个需要暴露接口的模块创建一个新的 API 模块，最好是不要把所有的 API 混在一个模块中
